## what is numpy?

numpy stands for numerical python
numpy is a fundemental package for scientific computation/programming.

scintific progrmaning deals with solving scientitific or mathematical problem with help of computers-scintific 

when we want to use scientific computing in python we need to import these package


## why numpy?

1)Basic scientific programing operations:
arrays(numerical process on multidimensional array)
matrices
intehgration
diff equ
stats
and much more

## Applications of numpy

1)Array:mathematiacal and logical operation on array
2)operation relating to linear algbera
3)Random number generation
4)Broadcasting:number by number operation

diff between lists and arrats
similarties:
sore data
mutable
can be indexed and iterable
slices
1)disiliatrtes:
list:hetrogenous
arr:homogenious

## diff in operations

In [4]:

import numpy as np
a = np.array([1,2,3,4,5,6])
print(a/2)

[0.5 1.  1.5 2.  2.5 3. ]


In [5]:
list1
list1=[1,2,3,4]
primt(list1/2)

NameError: name 'list1' is not defined

## ADVANTAGES OF ARRAY OVER THE LIST

Less memory
fast
more convient for mathe,atical operations

array are not built in python
lists are bulit in python array

In [ ]:
Array():
"creating Array from lists and tuples"

In [6]:
import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [8]:
one_Dim = np.array([1,2,3])
print(one_Dim)

[1 2 3]


In [11]:
two_Dim = np.array([[1,2],[3,4]])
print(two_Dim)

[[1 2]
 [3 4]]


In [13]:
dt = np.array([1,2,3],"complex")
print(dt)

[1.+0.j 2.+0.j 3.+0.j]


In [15]:
using_tuple = np.array((1,2,3))
print(using_tuple)

[1 2 3]


In [ ]:
Different ways for creating numpy arrays:
    Array()                 ones()
    Arange()                Eye()
    Zeros()                Random()

## Arrange

In [17]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [19]:
arr_ev = np.arange(1,10,2)
print(arr_ev)

[1 3 5 7 9]


In [21]:
dt = np.arange(20,dtype= 'complex')
print(dt)

[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j
  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j 16.+0.j 17.+0.j
 18.+0.j 19.+0.j]


In [22]:
all_par = np.arange(1,10,2,dtype = 'float')
print(all_par)

[1. 3. 5. 7. 9.]


## Zeros

In [ ]:
ceating array filled with all zeros

In [23]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [25]:
b = np.zeros(3,dtype='int')
print(b)

[0 0 0]


In [28]:
c = np.zeros((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


In [30]:
d = np.zeros([3,4])
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
f = np.zeros(4,order='F')
print(f)

[0. 0. 0. 0.]


In [32]:
g=np.zeros((3,4),order='F')
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Ones

In [ ]:
ones(shape,dtype=none,order='m')

In [33]:
h = np.ones(3)
print(h)

[1. 1. 1.]


In [35]:
i=np.ones(3,dtype="int")
print(i)

[1 1 1]


In [36]:
j = np.empty([3,4],dtype="int")
print(j)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Line space

In [40]:
ls =  np.linspace(1,100,num=5)

In [ ]:
we will get equally spaced values from 1 to 100 the space is 5

In [41]:
print(ls)

[  1.    25.75  50.5   75.25 100.  ]


In [42]:
enls =  np.linspace(1,100,num=5,endpoint=False)
print(enls)

[ 1.  20.8 40.6 60.4 80.2]


In [46]:
enlr = np.linspace(1,100,num=4,retstep=True)##which gives the differnce
print(enlr)

(array([  1.,  34.,  67., 100.]), 33.0)


In [49]:
enlrd = np.linspace(1,100,num=4,dtype=int)
print(enlrd)

[  1  34  67 100]


In [52]:
np.linspace(1,10) ## default 50

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Eye

# Returns array filled with zeros except in the k-the diagonal whose values are equal to1

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [55]:
np.eye(4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [56]:
np.eye(4,k=-2)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [57]:
np.eye(4,k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [58]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [59]:
np.eye(4,k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
np.eye(4,k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## random

In [ ]:
randn()-normal distr
randint()-uniform int-[0,low]
randf()-unifm float
rand()-uniform-[0.1]

In [ ]:
randn()
creats array of speciced shape and files it with random vapues as standaerd normal distribution

In [4]:
import numpy as np
print(np.random.rand(5,3))

[[0.99685728 0.58723929 0.16186173]
 [0.10263743 0.73426954 0.09692355]
 [0.50435354 0.71192799 0.2300874 ]
 [0.82880985 0.4323637  0.7117865 ]
 [0.50422562 0.24983699 0.57014233]]


In [11]:
print(np.random.ranf(2))

[0.44569769 0.34382086]


In [14]:
print(np.random.ranf((4,5)))

[[0.13198887 0.79032059 0.84105874 0.84162851 0.94160917]
 [0.82012723 0.18359351 0.92153378 0.12642435 0.98488157]
 [0.21105202 0.97750831 0.78075157 0.66474158 0.97280913]
 [0.53776053 0.32866888 0.1042487  0.44448094 0.19575316]]


In [21]:
print(np.random.randint(2,size=10))

[0 1 0 1 1 0 1 1 0 1]


In [22]:
print(np.random.randint(5,size=(2,4)))

[[2 3 4 3]
 [4 2 1 1]]


## Attributes of array

dimension
shape
size
Dtype
itemsize

In [24]:
import numpy as np
a = np.array([1,2,3])
a.ndim

1

In [27]:
b=np.array([[1,2,4],[2,3,4]])
b.ndim

2

In [ ]:
## no of rows and col

In [28]:
a.shape

(3,)

In [29]:
b.shape

(2, 3)

In [ ]:
## no of elements = row*col

In [30]:
a.dtype

dtype('int32')

In [31]:
a.size

3

In [32]:
a.itemsize

4

## indexing

In [34]:
a=np.array([1,2,3,4,5,6])
print(a[3])

4


In [36]:
print(a[-3])

4


In [40]:
d = np.array([[1,2,4],[3,4,5]])
print(d)

[[1 2 4]
 [3 4 5]]


In [41]:
print(d[0][1])

2


In [43]:
td=[[[1,2,3],[4,5,6],[7,8,9]]]
print(np.array(td))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


## slicing:collection of values

In [ ]:
a[start:end:step]

In [48]:
a=np.array([1,2,3,4,5,6,7])
print(a[1:4])

[2 3 4]


In [49]:
print(a[:])

[1 2 3 4 5 6 7]


In [50]:
print(a[1::2])

[2 4 6]


In [56]:
twod=np.array([[1,2,3,4],[5,6,7,8],[20,30,40,50]])

In [57]:
print(twod)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 30 40 50]]


In [58]:
print(twod[1:,1:])

[[ 6  7  8]
 [30 40 50]]


In [60]:
print(twod[1:,1:])

[[ 6  7  8]
 [30 40 50]]


In [61]:
print(twod[::,::2])

[[ 1  3]
 [ 5  7]
 [20 40]]


## Boolean indexing

In [63]:
bi = np.array([[1,2,-3],[-10,20,30],[3,-4,-4]])

In [64]:
print(bi)

[[  1   2  -3]
 [-10  20  30]
 [  3  -4  -4]]


In [66]:
bi[bi<0]*3

array([ -9, -30, -12, -12])

## arthematic operations

## broscating=helps in arrthematic operation array of differen size

In [ ]:
rules
1)